const ACTIONS = {
    SHOW_LOADER:"SHOW_LOADER",
    HIDE_LOADER:"HIDE_LOADER",
    ADD_ITEMS:"ADD_ITEMS",
    DELETE_ITEM:"DELETE_ITEM",
    EDIT_ITEM_TO_NEW_NAME:"EDIT_ITEM_TO_NEW_NAME",
    UPDATE_EDIT_SAVE_ICON:"UPDATE_EDIT_SAVE_ICON"
    
};

export default ACTIONS;